import esbuild from "esbuild";
import process from "process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { readFile, writeFile } from "node:fs/promises";
import { builtinModules } from "node:module";

const rootDir = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

// Earliest JS we can run. Parse of main.js happens before this; onload starts after module eval.
var __pidianLoadStartedAt = (typeof performance !== "undefined" && typeof performance.now === "function")
  ? performance.now()
  : Date.now();
if (typeof window !== "undefined") {
  window.__pidianLoadStartedAt = __pidianLoadStartedAt;
}

// Obsidian evals plugin code, so Node's __filename is Electron's asar — not this file.
// Point import.meta.url at a virtual path so Pi does not walk electron.asar for package.json.
// pathToFileURL keeps this absolute on Windows; a hardcoded file:///pidian-virtual/...
// throws "File URL path must be absolute" in fileURLToPath / createRequire.
var import_meta_url = require("node:url").pathToFileURL("/pidian-virtual/pi-coding-agent/main.js").href;

// Pi hides node builtins behind import(variable) so bundlers skip them.
// Obsidian's eval context cannot fetch \`node:fs\` as an ESM module.
// Static \`fs\` imports are aliased to a stub; keep dynamic node:fs off the real disk too.
function __pidianFsMissing(method) {
  var err = new Error("Pidian does not access the filesystem (" + method + ")");
  err.code = "ENOENT";
  return err;
}
var __pidianFsPromises = {
  readFile: async function () { throw __pidianFsMissing("readFile"); },
  writeFile: async function () { throw __pidianFsMissing("writeFile"); },
  mkdir: async function () { throw __pidianFsMissing("mkdir"); },
  stat: async function () { throw __pidianFsMissing("stat"); },
};
var __pidianFs = {
  existsSync: function () { return false; },
  constants: { F_OK: 0, R_OK: 4, W_OK: 2, X_OK: 1 },
  promises: __pidianFsPromises,
  readFileSync: function () { throw __pidianFsMissing("readFileSync"); },
  statSync: function () { throw __pidianFsMissing("statSync"); },
  mkdirSync: function () { throw __pidianFsMissing("mkdirSync"); },
  writeFileSync: function () { throw __pidianFsMissing("writeFileSync"); },
};
function __pidianDynImport(specifier) {
  var id = String(specifier);
  if (id === "fs" || id === "node:fs") {
    return Promise.resolve(__pidianFs);
  }
  if (id === "fs/promises" || id === "node:fs/promises") {
    return Promise.resolve(__pidianFsPromises);
  }
  if (id.indexOf("node:") === 0) {
    return Promise.resolve(require(id.slice(5)));
  }
  return import(id);
}
`;

const stubDir = path.join(rootDir, "src/infrastructure/pi/stubs");
const stubPaths = {
  jiti: path.join(stubDir, "jiti.js"),
  highlight: path.join(stubDir, "highlight.js"),
  photon: path.join(stubDir, "photon.js"),
  tui: path.join(stubDir, "pi-tui.js"),
  mermaid: path.join(stubDir, "mermaid.js"),
  resourceLoader: path.join(rootDir, "src/infrastructure/pi/PidianResourceLoader.ts"),
  sdk: path.join(rootDir, "src/infrastructure/pi/piCodingAgentSdk.ts"),
  extensionLoader: path.join(stubDir, "extension-loader.js"),
  tools: path.join(stubDir, "pi-tools.js"),
  bash: path.join(stubDir, "bash.js"),
  bashExecutor: path.join(stubDir, "bash-executor.js"),
  childProcess: path.join(stubDir, "child-process.js"),
  fs: path.join(stubDir, "fs.ts"),
  fsPromises: path.join(stubDir, "fs-promises.ts"),
  toolsManager: path.join(stubDir, "tools-manager.js"),
  windowsSelfUpdate: path.join(stubDir, "windows-self-update.js"),
  shell: path.join(stubDir, "shell.js"),
  resolveConfigValue: path.join(stubDir, "resolve-config-value.ts"),
  exec: path.join(stubDir, "exec.js"),
};

function fromPiCodingAgent(args) {
  const importer = args.importer.replaceAll("\\", "/");
  return importer.includes("@earendil-works/pi-coding-agent");
}

const obsidianCompatPlugin = {
  name: "obsidian-compat",
  setup(build) {
    // Rewrite Pi's import(variable) of node builtins to require().
    build.onLoad({ filter: /[@]earendil-works[/\\]pi-ai[/\\].*\.js$/ }, async (args) => {
      let contents = await readFile(args.path, "utf8");
      contents = contents.replaceAll(
        "import(__rewriteRelativeImportExtension(",
        "__pidianDynImport(__rewriteRelativeImportExtension(",
      );
      contents = contents.replaceAll('import("node:', '__pidianDynImport("node:');
      contents = contents.replaceAll("import('node:", "__pidianDynImport('node:");
      return { contents, loader: "js" };
    });

    // The package barrel re-exports the CLI. Import only the SDK surface.
    build.onResolve({ filter: /^@earendil-works\/pi-coding-agent$/ }, () => ({
      path: stubPaths.sdk,
    }));
    build.onResolve({ filter: /[@]earendil-works[/\\]pi-coding-agent[/\\]dist[/\\]index\.js$/ }, () => ({
      path: stubPaths.sdk,
    }));

    // DefaultResourceLoader pulls the extension loader, which imports the whole
    // Pi barrel (CLI, TUI, jiti). Pidian only needs prompt + AGENTS.md.
    build.onResolve({ filter: /(?:^|[\\/])resource-loader\.js$/ }, (args) => {
      if (!fromPiCodingAgent(args)) {
        return undefined;
      }
      return { path: stubPaths.resourceLoader };
    });

    // Replace resolved Pi modules. onLoad matches the file path, not the specifier,
    // so `./loader.js` from extensions/index.js is still caught.
    const piFileStubs = [
      ["core/extensions/loader.js", stubPaths.extensionLoader],
      ["core/tools/index.js", stubPaths.tools],
      ["core/tools/bash.js", stubPaths.bash],
      ["core/bash-executor.js", stubPaths.bashExecutor],
      ["utils/child-process.js", stubPaths.childProcess],
      ["utils/tools-manager.js", stubPaths.toolsManager],
      ["utils/windows-self-update.js", stubPaths.windowsSelfUpdate],
      ["utils/shell.js", stubPaths.shell],
      ["core/resolve-config-value.js", stubPaths.resolveConfigValue],
      ["core/exec.js", stubPaths.exec],
    ];
    for (const [relative, stubPath] of piFileStubs) {
      const escaped = relative.replaceAll(".", "\\.").replaceAll("/", "[/\\\\]");
      const filter = new RegExp(`[@]earendil-works[/\\\\]pi-coding-agent[/\\\\]dist[/\\\\]${escaped}$`);
      build.onLoad({ filter }, async () => {
        const contents = await readFile(stubPath, "utf8");
        return { contents, loader: stubPath.endsWith(".ts") ? "ts" : "js" };
      });
    }

    // AgentSession still imports TUI themes and coding-tool renderers.
    build.onResolve({ filter: /^(jiti|jiti\/)/ }, () => ({ path: stubPaths.jiti }));
    build.onResolve({ filter: /^highlight\.js/ }, () => ({ path: stubPaths.highlight }));
    build.onResolve({ filter: /^@silvia-odwyer\/photon-node/ }, () => ({ path: stubPaths.photon }));
    build.onResolve({ filter: /^@earendil-works\/pi-tui/ }, () => ({ path: stubPaths.tui }));
    build.onResolve({ filter: /^grok-mermaid/ }, () => ({ path: stubPaths.mermaid }));

    // React 19 hoistable resources (preinit / <script>) call createElement("script")
    // in three places. Pidian only uses createRoot for the sidebar and never
    // preloads scripts; Obsidian review rejects the literal anyway. Replace the
    // DOM injection with a throw so the API cannot load external code.
    const expectedReactDomScriptSites = 3;
    build.onLoad(
      { filter: /[\\/]react-dom[\\/]cjs[\\/]react-dom-client\.(production|development)\.js$/ },
      async (args) => {
        const contents = await readFile(args.path, "utf8");
        const reactDomScriptCreate = /\w+\.createElement\("script"\)/g;
        const sites = contents.match(reactDomScriptCreate);
        if (sites?.length !== expectedReactDomScriptSites) {
          throw new Error(
            `Expected ${expectedReactDomScriptSites} createElement("script") sites in ${args.path}, found ${sites?.length ?? 0}`,
          );
        }
        return {
          contents: contents.replace(
            /\w+\.createElement\("script"\)/g,
            '(() => { throw new Error("Pidian does not inject script elements"); })()',
          ),
          loader: "js",
        };
      },
    );
  },
};

const FORBIDDEN_BUNDLE_PATTERNS = [
  { pattern: /extractZipArchive/, label: "ZIP extraction (Pi tools-manager)" },
  { pattern: /quarantineWindowsNativeDependencies/, label: "Pi Windows self-update" },
  { pattern: /require\(["']child_process["']\)/, label: "require('child_process')" },
  { pattern: /require\(["']node:child_process["']\)/, label: "require('node:child_process')" },
  { pattern: /from["']child_process["']/, label: "import from child_process" },
  { pattern: /from["']node:child_process["']/, label: "import from node:child_process" },
  { pattern: /require\(["']fs["']\)/, label: "require('fs')" },
  { pattern: /require\(["']node:fs["']\)/, label: "require('node:fs')" },
  { pattern: /require\(["']fs\/promises["']\)/, label: "require('fs/promises')" },
  { pattern: /require\(["']node:fs\/promises["']\)/, label: "require('node:fs/promises')" },
  { pattern: /\bos\.hostname\b/, label: "os.hostname" },
  { pattern: /\bos\.userInfo\b/, label: "os.userInfo" },
  { pattern: /\bos\.networkInterfaces\b/, label: "os.networkInterfaces" },
  { pattern: /createElement\(\s*["'`]script["'`]\s*\)/i, label: "dynamic <script> element creation" },
  { pattern: /linkedom/, label: "linkedom (use DOMParser)" },
];

function groupMetafileInput(file) {
  const normalized = file.replaceAll("\\", "/");
  const pi = normalized.match(/@earendil-works\/pi-coding-agent\/(?:dist\/)?(.+)$/);
  if (pi) {
    const parts = pi[1].split("/");
    const top = parts.slice(0, Math.min(2, parts.length)).join("/");
    return `@earendil-works/pi-coding-agent/${top}`;
  }
  const pnpm = normalized.match(/node_modules\/\.pnpm\/[^/]+\/node_modules\/(@[^/]+\/[^/]+|[^/]+)/);
  if (pnpm) {
    return pnpm[1];
  }
  const nm = normalized.match(/node_modules\/(@[^/]+\/[^/]+|[^/]+)/);
  if (nm) {
    return nm[1];
  }
  if (normalized.includes("/src/")) {
    return "src/";
  }
  return normalized;
}

function printMetafileSummary(metafile) {
  const groups = new Map();
  for (const [file, info] of Object.entries(metafile.inputs)) {
    const group = groupMetafileInput(file);
    groups.set(group, (groups.get(group) ?? 0) + info.bytes);
  }
  const ranked = [...groups.entries()].sort((a, b) => b[1] - a[1]);
  const outputs = Object.entries(metafile.outputs);
  for (const [file, info] of outputs) {
    console.log(`bundle ${file}: ${formatKb(info.bytes)}`);
  }
  console.log("top inputs:");
  for (const [group, bytes] of ranked.slice(0, 25)) {
    console.log(`  ${formatKb(bytes).padStart(8)}  ${group}`);
  }
}

function formatKb(bytes) {
  return `${(bytes / 1024).toFixed(1)}kb`;
}

async function assertBundleSurface() {
  const bundle = await readFile(path.join(rootDir, "main.js"), "utf8");
  const hits = FORBIDDEN_BUNDLE_PATTERNS.filter(({ pattern }) => pattern.test(bundle));
  if (hits.length === 0) {
    return;
  }
  const details = hits.map(({ label }) => `  - ${label}`).join("\n");
  throw new Error(`Pidian bundle still contains review-sensitive APIs:\n${details}`);
}

const prod = process.argv[2] === "production";
const analyze = process.argv.includes("analyze");

const nodeExternals = [
  ...builtinModules,
  ...builtinModules.map((name) => `node:${name}`),
];

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...nodeExternals,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  metafile: analyze,
  jsx: "automatic",
  platform: "node",
  plugins: [obsidianCompatPlugin],
  alias: {
    // Pi pulls undici via SettingsManager. Real undici uses Node Timeout.unref()
    // and HTTP/2 pings; both throw in Electron's renderer.
    undici: path.join(rootDir, "src/infrastructure/http/undici-stub.js"),
    // google-auth-library optionally shells out to gcloud. Keep it out of the bundle.
    child_process: stubPaths.childProcess,
    "node:child_process": stubPaths.childProcess,
    fs: stubPaths.fs,
    "node:fs": stubPaths.fs,
    "fs/promises": stubPaths.fsPromises,
    "node:fs/promises": stubPaths.fsPromises,
  },
  define: {
    "import.meta.url": "import_meta_url",
    ...(prod ? { "process.env.NODE_ENV": '"production"' } : {}),
  },
});

if (prod) {
  const result = await context.rebuild();
  if (analyze) {
    if (!result.metafile) {
      throw new Error("analyze requested but esbuild did not produce a metafile");
    }
    await writeFile(path.join(rootDir, "meta.json"), JSON.stringify(result.metafile));
    printMetafileSummary(result.metafile);
  }
  await assertBundleSurface();
  process.exit(0);
} else {
  await context.watch();
}
