import esbuild from "esbuild";
import process from "process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { readFile } from "node:fs/promises";
import { builtinModules } from "node:module";

const rootDir = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

// Obsidian evals plugin code, so Node's __filename is Electron's asar — not this file.
// Pi reads package.json from import.meta.url / PI_PACKAGE_DIR at module load and throws
// "Invalid package .../electron.asar" if that path is inside the asar.
(function () {
  var path = require("path");
  var os = require("os");
  var fs = require("fs");
  var dir = path.join(os.tmpdir(), "pidian-pi-package");
  try {
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(
      path.join(dir, "package.json"),
      JSON.stringify({
        name: "@earendil-works/pi-coding-agent",
        version: "0.0.0",
        piConfig: { name: "pi", configDir: ".pi" },
      })
    );
  } catch (e) {}
  if (!process.env.PI_PACKAGE_DIR) {
    process.env.PI_PACKAGE_DIR = dir;
  }
})();
var import_meta_url = require("url").pathToFileURL(
  require("path").join(process.env.PI_PACKAGE_DIR, "main.js")
).href;

// Pi hides node builtins behind import(variable) so bundlers skip them.
// Obsidian's eval context cannot fetch \`node:fs\` as an ESM module.
function __pidianDynImport(specifier) {
  var id = String(specifier);
  if (id.indexOf("node:") === 0) {
    return Promise.resolve(require(id.slice(5)));
  }
  return import(id);
}
`;

const stubDir = path.join(rootDir, "src/infrastructure/pi/stubs");
const stubPaths = {
  jiti: path.join(stubDir, "jiti.js"),
  highlight: path.join(stubDir, "highlight.js"),
  photon: path.join(stubDir, "photon.js"),
  tui: path.join(stubDir, "pi-tui.js"),
  mermaid: path.join(stubDir, "mermaid.js"),
  resourceLoader: path.join(rootDir, "src/infrastructure/pi/PidianResourceLoader.ts"),
};

const obsidianCompatPlugin = {
  name: "obsidian-compat",
  setup(build) {
    // Rewrite Pi's import(variable) of node builtins to require().
    build.onLoad({ filter: /[@]earendil-works[/\\]pi-ai[/\\].*\.js$/ }, async (args) => {
      let contents = await readFile(args.path, "utf8");
      contents = contents.replaceAll(
        "import(__rewriteRelativeImportExtension(",
        "__pidianDynImport(__rewriteRelativeImportExtension(",
      );
      return { contents, loader: "js" };
    });

    // DefaultResourceLoader pulls the extension loader, which imports the whole
    // Pi barrel (CLI, TUI, jiti). Pidian only needs prompt + AGENTS.md.
    build.onResolve({ filter: /(?:^|[\\/])resource-loader\.js$/ }, (args) => {
      const importer = args.importer.replaceAll("\\", "/");
      if (!importer.includes("@earendil-works/pi-coding-agent")) {
        return undefined;
      }
      return { path: stubPaths.resourceLoader };
    });

    // AgentSession still imports TUI themes and coding-tool renderers.
    build.onResolve({ filter: /^(jiti|jiti\/)/ }, () => ({ path: stubPaths.jiti }));
    build.onResolve({ filter: /^highlight\.js/ }, () => ({ path: stubPaths.highlight }));
    build.onResolve({ filter: /^@silvia-odwyer\/photon-node/ }, () => ({ path: stubPaths.photon }));
    build.onResolve({ filter: /^@earendil-works\/pi-tui/ }, () => ({ path: stubPaths.tui }));
    build.onResolve({ filter: /^grok-mermaid/ }, () => ({ path: stubPaths.mermaid }));
  },
};

const prod = process.argv[2] === "production";

const nodeExternals = [
  ...builtinModules,
  ...builtinModules.map((name) => `node:${name}`),
];

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...nodeExternals,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  jsx: "automatic",
  platform: "node",
  plugins: [obsidianCompatPlugin],
  alias: {
    // Pi pulls undici via SettingsManager. Real undici uses Node Timeout.unref()
    // and HTTP/2 pings; both throw in Electron's renderer.
    undici: path.join(rootDir, "src/infrastructure/http/undici-stub.js"),
  },
  define: {
    "import.meta.url": "import_meta_url",
    ...(prod ? { "process.env.NODE_ENV": '"production"' } : {}),
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
