import esbuild from "esbuild";
import process from "process";
import { readFile } from "node:fs/promises";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

// Obsidian evals plugin code, so Node's __filename is Electron's asar — not this file.
// Pi reads package.json from import.meta.url / PI_PACKAGE_DIR at module load and throws
// "Invalid package .../electron.asar" if that path is inside the asar.
(function () {
  var path = require("path");
  var os = require("os");
  var fs = require("fs");
  var dir = path.join(os.tmpdir(), "pidian-pi-package");
  try {
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(
      path.join(dir, "package.json"),
      JSON.stringify({
        name: "@earendil-works/pi-coding-agent",
        version: "0.0.0",
        piConfig: { name: "pi", configDir: ".pi" },
      })
    );
  } catch (e) {}
  if (!process.env.PI_PACKAGE_DIR) {
    process.env.PI_PACKAGE_DIR = dir;
  }
})();
var import_meta_url = require("url").pathToFileURL(
  require("path").join(process.env.PI_PACKAGE_DIR, "main.js")
).href;

// Pi hides node builtins behind import(variable) so bundlers skip them.
// Obsidian's eval context cannot fetch \`node:fs\` as an ESM module.
function __pidianDynImport(specifier) {
  var id = String(specifier);
  if (id.indexOf("node:") === 0) {
    return Promise.resolve(require(id.slice(5)));
  }
  return import(id);
}
`;

const obsidianCompatPlugin = {
  name: "obsidian-compat",
  setup(build) {
    // Electron's worker_threads has no markAsUncloneable; undici calls it at load.
    build.onLoad({ filter: /undici[/\\]lib[/\\]web[/\\]webidl[/\\]index\.js$/ }, async (args) => {
      let contents = await readFile(args.path, "utf8");
      contents = contents.replace(
        "const { markAsUncloneable } = require('node:worker_threads')",
        "const { markAsUncloneable = () => {} } = (() => { try { return require('node:worker_threads'); } catch { return {}; } })()",
      );
      return { contents, loader: "js" };
    });

    // Rewrite Pi's import(variable) of node builtins to require().
    build.onLoad({ filter: /[@]earendil-works[/\\]pi-ai[/\\].*\.js$/ }, async (args) => {
      let contents = await readFile(args.path, "utf8");
      contents = contents.replaceAll(
        "import(__rewriteRelativeImportExtension(",
        "__pidianDynImport(__rewriteRelativeImportExtension(",
      );
      return { contents, loader: "js" };
    });
  },
};

const prod = process.argv[2] === "production";

const nodeExternals = [
  ...builtinModules,
  ...builtinModules.map((name) => `node:${name}`),
];

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...nodeExternals,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  jsx: "automatic",
  platform: "node",
  plugins: [obsidianCompatPlugin],
  define: {
    "import.meta.url": "import_meta_url",
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
