allowBuilds:
  "@google/genai": true
  esbuild: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@earendil-works/chord@0.87.0'
  - '@earendil-works/pi-agent-core@0.87.0'
  - '@earendil-works/pi-ai@0.87.0'
  - '@earendil-works/pi-coding-agent@0.87.0'
  - '@earendil-works/pi-telemetry@0.87.0'
  - '@earendil-works/pi-tui@0.87.0'
onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - "@google/genai"
